### ISSUE TITLE
Missing licensing to iTwinUI

### ISSUE THREAD

**Issue by bentleyvk** [BlameDeng/vue-viewer-components#1]
Hi @BlameDeng, I see that you are using iTwinUI-CSS package which is really nice but your code is almost identical to [iTwinUI-react](https://github.com/iTwin/iTwinUI-react) that we own. iTwinUI has MIT license that allows copying and modifying but you must include our [license](https://github.com/iTwin/iTwinUI-react/blob/main/LICENSE.md) in your code.

**Comment by BlameDeng** [comment]
Sure, added.
